In [1]:
#__________________________IMPORTANT FUNCTIONS________________________________

# np.sort() => To sort  an array . 
# np.append("name of the array" , no. u want to append) => To add a value in the end of an array.
# np.concatenate() => It concats 2 arrays on the basis of some axis value => vertically or horizontallly.
# np.unique() => With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
# np.expand_dims() => With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.
# np.where(condition , if true , otherwise) => The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
# np.argmax() / np.argmin() => The numpy.argmax()/np.argmin() function returns indices of the max/min element of the array in a particular axis.
# np.cumsum() => numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.
# np.cumprod() => numpy.cumprod() function is used when we want to compute the cumulative sum of array elements over a given axis.
# np.percentile() => numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.
# np.histogram() => Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.
# np.corrcoef() => Return Pearson product-moment correlation coefficients.
# np.isin()  => With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.
# np.flip() =>The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
# np.put(array name , [indecies to change] , [new values]) => The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.
# np.delete(array name , index) => The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.
# np.clip() => numpy.clip() function is used to Clip (limit) the values in an array.

In [2]:
import numpy as np 
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [3]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [4]:
b

array([[14, 66, 99, 73],
       [19,  4, 29, 96],
       [27, 72, 62, 70],
       [29, 88, 48, 29],
       [38, 64, 88, 61],
       [23,  5, 86, 77]])

#### np.sort()

In [5]:
np.sort(a)

array([16, 23, 31, 34, 34, 36, 43, 46, 47, 48, 52, 67, 69, 76, 88])

In [6]:
np.sort(a)[::-1]

array([88, 76, 69, 67, 52, 48, 47, 46, 43, 36, 34, 34, 31, 23, 16])

In [7]:
np.sort(b , axis=0) # column wise sorting 

array([[14,  4, 29, 29],
       [19,  5, 48, 61],
       [23, 64, 62, 70],
       [27, 66, 86, 73],
       [29, 72, 88, 77],
       [38, 88, 99, 96]])

In [8]:
np.sort(b) # Row wise sorting

array([[14, 66, 73, 99],
       [ 4, 19, 29, 96],
       [27, 62, 70, 72],
       [29, 29, 48, 88],
       [38, 61, 64, 88],
       [ 5, 23, 77, 86]])

#### np.append()

In [9]:
np.append(a , 200)

array([ 67,  43,  76,  36,  46,  48,  16,  88,  34,  47,  52,  69,  34,
        31,  23, 200])

In [10]:
#2-d array

np.append(b ,np.ones((b.shape[0] , 1)) , axis=1)

array([[14., 66., 99., 73.,  1.],
       [19.,  4., 29., 96.,  1.],
       [27., 72., 62., 70.,  1.],
       [29., 88., 48., 29.,  1.],
       [38., 64., 88., 61.,  1.],
       [23.,  5., 86., 77.,  1.]])

#### np.concatenate()

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6 ,12).reshape(2,3)

In [12]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d) , axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d) , axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### np.unique()

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### np.expand_dims()

In [18]:
 a 

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [19]:
a.shape

(15,)

In [20]:
np.expand_dims(a  , axis=0)

array([[67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23]])

In [21]:
np.expand_dims(a  , axis=0).shape

(1, 15)

#### np.where()

In [22]:
a


array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [23]:
# Q. Give  the index element of all the numbers which are grater than 50.

np.where(a>50)

(array([ 0,  2,  7, 10, 11], dtype=int64),)

In [24]:
# Q. Replace the  elements which are grater than 50 with 0.
np.where(a>50 , 0 , a)

array([ 0, 43,  0, 36, 46, 48, 16,  0, 34, 47,  0,  0, 34, 31, 23])

In [25]:
# Q. Replace the even elements with 0.
np.where(a%2 == 0,0,a)

array([67, 43,  0,  0,  0,  0,  0,  0,  0, 47,  0, 69,  0, 31, 23])

#### np.argmax()

In [26]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [27]:
np.argmax(a)

7

In [28]:
b

array([[14, 66, 99, 73],
       [19,  4, 29, 96],
       [27, 72, 62, 70],
       [29, 88, 48, 29],
       [38, 64, 88, 61],
       [23,  5, 86, 77]])

In [29]:
np.argmax(b , axis=0)

array([4, 3, 0, 1], dtype=int64)

In [30]:
np.argmax(b , axis=1)

array([2, 3, 1, 1, 2, 2], dtype=int64)

#### np.argmin()

In [31]:
np.argmin(a)

6

In [32]:
np.argmin(b , axis=0)

array([0, 1, 1, 3], dtype=int64)

In [33]:
np.argmin(b , axis=1)

array([0, 1, 0, 0, 0, 1], dtype=int64)

#### np.cumsum()

In [34]:
np.cumsum(a)

array([ 67, 110, 186, 222, 268, 316, 332, 420, 454, 501, 553, 622, 656,
       687, 710])

In [35]:
np.cumsum(b)

array([  14,   80,  179,  252,  271,  275,  304,  400,  427,  499,  561,
        631,  660,  748,  796,  825,  863,  927, 1015, 1076, 1099, 1104,
       1190, 1267])

In [36]:
np.cumsum(b , axis=1)

array([[ 14,  80, 179, 252],
       [ 19,  23,  52, 148],
       [ 27,  99, 161, 231],
       [ 29, 117, 165, 194],
       [ 38, 102, 190, 251],
       [ 23,  28, 114, 191]])

In [37]:
np.cumsum(b , axis=0)

array([[ 14,  66,  99,  73],
       [ 33,  70, 128, 169],
       [ 60, 142, 190, 239],
       [ 89, 230, 238, 268],
       [127, 294, 326, 329],
       [150, 299, 412, 406]])

#### np.cumprod()

In [38]:
np.cumprod(a)

array([         67,        2881,      218956,     7882416,   362591136,
         224505344,  -702881792, -1724055552,  1511653376, -1966735360,
         808976384,   -15204352,  -516947968,  1154482176,   783286272])

#### np.percentile()

In [39]:
a 

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [40]:
np.percentile(a , 50)

46.0

In [41]:
np.percentile(a , 75)

59.5

In [42]:
np.median(a)

46.0

#### np.histogram()

In [43]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [46]:
bins = 10*(np.arange(11))
np.histogram(a , bins=bins)

(array([0, 1, 1, 4, 4, 1, 2, 1, 1, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [47]:
np.histogram(a , bins=[0,50 , 100])

(array([10,  5], dtype=int64), array([  0,  50, 100]))

#### np.corrcoef()

In [48]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#### np.isin()

In [49]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [52]:
items = [10 , 31 , 76 , 50 , 88 , 97 , 86 , 22 , 52]

In [53]:
np.isin(a , items)

array([False, False,  True, False, False, False, False,  True, False,
       False,  True, False, False,  True, False])

In [54]:
a[np.isin(a , items)]

array([76, 88, 52, 31])

#### np.flip()

In [55]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [56]:
b

array([[14, 66, 99, 73],
       [19,  4, 29, 96],
       [27, 72, 62, 70],
       [29, 88, 48, 29],
       [38, 64, 88, 61],
       [23,  5, 86, 77]])

In [57]:
np.flip(a)

array([23, 31, 34, 69, 52, 47, 34, 88, 16, 48, 46, 36, 76, 43, 67])

In [59]:
np.flip(b)

array([[77, 86,  5, 23],
       [61, 88, 64, 38],
       [29, 48, 88, 29],
       [70, 62, 72, 27],
       [96, 29,  4, 19],
       [73, 99, 66, 14]])

In [60]:
np.flip(b , axis=1)

array([[73, 99, 66, 14],
       [96, 29,  4, 19],
       [70, 62, 72, 27],
       [29, 48, 88, 29],
       [61, 88, 64, 38],
       [77, 86,  5, 23]])

In [61]:
np.flip(b , axis=0)

array([[23,  5, 86, 77],
       [38, 64, 88, 61],
       [29, 88, 48, 29],
       [27, 72, 62, 70],
       [19,  4, 29, 96],
       [14, 66, 99, 73]])

#### np.put()

In [62]:
a

array([67, 43, 76, 36, 46, 48, 16, 88, 34, 47, 52, 69, 34, 31, 23])

In [63]:
np.put(a , [0,1] , [100 , 100])

In [64]:
a

array([100, 100,  76,  36,  46,  48,  16,  88,  34,  47,  52,  69,  34,
        31,  23])

#### np.delete()

In [65]:
a

array([100, 100,  76,  36,  46,  48,  16,  88,  34,  47,  52,  69,  34,
        31,  23])

In [66]:
np.delete(a,0)

array([100,  76,  36,  46,  48,  16,  88,  34,  47,  52,  69,  34,  31,
        23])

In [67]:
np.delete(a,[0,2,4])

array([100,  36,  48,  16,  88,  34,  47,  52,  69,  34,  31,  23])

#### Set Functions

In [68]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.intersect1d(m,n)

array([3, 4, 5])

In [71]:
np.setdiff1d(n,m)

array([6, 7])

In [72]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [73]:
m[np.in1d(m,1)]

array([1])

#### np.clip

In [74]:
a

array([100, 100,  76,  36,  46,  48,  16,  88,  34,  47,  52,  69,  34,
        31,  23])

In [75]:
np.clip(a , a_min=25 , a_max=75)

array([75, 75, 75, 36, 46, 48, 25, 75, 34, 47, 52, 69, 34, 31, 25])