### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
# np.array() => Used to create numpy array.
# np.arange() => used to create numpy array in a range (first included , last not included) . ex = an array having elements from 1 to 10.
# .reshape() => This is used to reshape an array from one size to another .
# np.ones() => It will initiate an array of give sizes with all the elements as 1 .
# np.zeroes() => It will initiate an array of give sizes with all the elements as 2 .
#

## Creating Numpy Arrays


In [2]:
import numpy as np 

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

### 2D or 3d Array

In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
c= np.array([[1 , 2],[3,4],[7,8]])
c

array([[1, 2],
       [3, 4],
       [7, 8]])

In [12]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#dtype
np.array([8 , 6 , 12] , dtype=float)

array([ 8.,  6., 12.])

### np.arange()

In [13]:
np.arange(1 , 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(1 , 12 , 2)

array([ 1,  3,  5,  7,  9, 11])

### .reshape()

In [16]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
a.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### np.ones() or np.zeroes()

In [20]:
np.ones((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])