### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [127]:
#-----------------Creating a Numpy Array-------------

# np.array() => Used to create numpy array.
# np.arange() => used to create numpy array in a range (first included , last not included) . ex = an array having elements from 1 to 10.
# .reshape() => This is used to reshape an array from one size to another .
# np.ones() => It will initiate an array of give sizes with all the elements as 1 .
# np.zeroes() => It will initiate an array of give sizes with all the elements as 0 .
# np.random() => It will initiate an array of give sizes with all the elements randomly between 0 and 1.
# np.linspace(lower bound , upper bound , no. of points) => Generates linearly spaced points between given ranges and no. of points.
# np.identity() => Used to create a identity matrix of given size.

#-----------------Numpy Attributes------------------

# ndim => to know the dimension of the given arrray.
# shape => This gives us the shape of the given array .
# size => This gives us the size or total no. of elements of the given array.
# itemsize => it gives us the size of the numpy array in the memory. 
# astype() => it is used to change the data type . 

#-----------------Numpy Functions-------------------

# max / min / sum / prod  => np.max()
# mean / median / var / std => np.mean()
# dot product => np.dot()
# log / exp  => np.exp() , np.log()
# round / floor / ceil => np.floor() , np.round()

#----------------Some More Important Functions-----

# np.nditer() => This is used to go to each items of the 2-d or 3-d array.
# array.T => To take the transpose of the array 
# array.ravel => To convert any dimension array into 1-d array 
# Stacking => np.hstack() , np.vstack() 
# Spliting => np.hsplit() , np.vsplit()

## Creating Numpy Arrays


In [2]:
import numpy as np 

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

### 2D or 3d Array

In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c= np.array([[1 , 2],[3,4],[7,8]])
c

array([[1, 2],
       [3, 4],
       [7, 8]])

In [9]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#dtype
np.array([8 , 6 , 12] , dtype=float)

array([ 8.,  6., 12.])

### np.arange()

In [11]:
np.arange(1 , 12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(1 , 12 , 2)

array([ 1,  3,  5,  7,  9, 11])

### .reshape()

In [13]:
np.arange(8,20).reshape(3,4)

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
a.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### np.ones() or np.zeroes()

In [16]:
np.ones((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones(([3,4,2]))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
np.zeros((3 , 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.random

In [19]:
np.random.random((3,5))

array([[0.63880721, 0.3001734 , 0.53028848, 0.82996636, 0.23861594],
       [0.32445476, 0.49702847, 0.83934958, 0.9870533 , 0.67779472],
       [0.35507958, 0.03605527, 0.28723666, 0.20221997, 0.74362377]])

### np.linspace()

In [20]:
np.linspace(1, 30 , 5)

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

### np.identity

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Attributes

In [22]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

### ndim

In [23]:
a1.ndim

1

In [24]:
a2.ndim

2

In [25]:
a3.ndim

3

### shape

In [26]:
a1.shape

(10,)

In [27]:
a2.shape

(3, 4)

In [28]:
a3.shape # => Gives us the shape as (no. of dimensions , rows , columns)

(2, 2, 2)

### size

In [29]:
a1.size

10

In [30]:
a2.size

12

In [31]:
a3.size

8

#### itemsize

In [32]:
a1.itemsize

8

In [33]:
a2.itemsize

8

In [34]:
a3.itemsize

4

### Change Data Type 

In [35]:
a1.dtype

dtype('int64')

In [36]:
a1.astype(np.int32).dtype

dtype('int32')

### Array Operations

In [37]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

#### Scalar Operations

In [38]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [39]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [40]:
a2 >16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
a1 == 7 


array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

#### Vector Operations

In [42]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [43]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Array Functions 

In [44]:
a1 = np.random.random((3,3))

In [45]:
a1

array([[0.55026312, 0.49802751, 0.30244866],
       [0.3921543 , 0.86857005, 0.95836632],
       [0.57684782, 0.40505121, 0.39956249]])

In [46]:
a1 = np.round(a1*100)

In [47]:
a1

array([[55., 50., 30.],
       [39., 87., 96.],
       [58., 41., 40.]])

#### min / max / sum / prod

In [48]:
np.min(a1)

30.0

In [49]:
np.max(a1)

96.0

In [50]:
np.sum(a1)

496.0

In [51]:
np.prod(a1)

2556117907200000.0

In [52]:
# We can apply the above functions column as well row wise too
# column wise operation =>  axis =0
# row wise operation =>  axis =1

np.max(a1 , axis = 0)

array([58., 87., 96.])

In [53]:
np.sum(a1, axis =1)

array([135., 222., 139.])

#### statistical fucntions

In [54]:
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

55.111111111111114
50.0
21.189328784107055
448.9876543209877


In [55]:
print(np.mean(a1,  axis = 1))
print(np.median(a1,  axis = 1))
print(np.std(a1,  axis = 1))
print(np.var(a1,  axis = 1))

[45.         74.         46.33333333]
[50. 87. 41.]
[10.8012345  25.01999201  8.25967446]
[116.66666667 626.          68.22222222]


#### Dot Product

In [56]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(7,19).reshape(4,3)

In [57]:
np.dot(a1,a2)

array([[ 84,  90,  96],
       [268, 290, 312],
       [452, 490, 528]])

#### exp() / log()

In [58]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [59]:
np.log(a1)

C:\Users\Shrijeet Kumar\AppData\Local\Temp\ipykernel_18224\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

#### round() / ceil() / floor()

In [60]:
a1= (np.random.random((3,4)))*100
a1

array([[27.02697381, 79.12420167, 18.89547409, 36.94801453],
       [ 1.99418626,  5.55998076, 64.66507634, 88.05025698],
       [44.08553657, 63.5106567 , 78.02141443, 55.38549688]])

In [61]:
np.round(a1)

array([[27., 79., 19., 37.],
       [ 2.,  6., 65., 88.],
       [44., 64., 78., 55.]])

In [62]:
np.floor(a1)

array([[27., 79., 18., 36.],
       [ 1.,  5., 64., 88.],
       [44., 63., 78., 55.]])

In [63]:
np.ceil(a1)

array([[28., 80., 19., 37.],
       [ 2.,  6., 65., 89.],
       [45., 64., 79., 56.]])

### Indexing and Slicing

In [64]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [65]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### 1D array

In [68]:
a1[-1]

9

In [69]:
a1[0]

0

In [70]:
a1[0:3] # First included and last not included 

array([0, 1, 2])

In [71]:
a1[-4 : -1]

array([6, 7, 8])

#### 2D Array Indexing 

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a2[1 , 2] #=> a2[row , column]

6

In [75]:
a2[2 , 1]

9

#### 3D Array Indexing 

In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [79]:
a3[1 , 0 , 1] # a3[2d-matrix , row , column]

5

In [80]:
a3[0 , 1 , 0]

2

In [81]:
a3[0 , 0 ,0]

0

In [82]:
a3[1 , 1 , 0]

6

#### 2-D array Slicing 

In [84]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
# slice 1 , 2 , 5 , 6
a2[0:2 , 1:3]

array([[1, 2],
       [5, 6]])

In [89]:
# slice 0 , 2 , 8 , 10
a2[0::2 , 0::2]

array([[ 0,  2],
       [ 8, 10]])

In [91]:
# slice 5 , 7 , 9 , 10
a2[1: , 1::2]

array([[ 5,  7],
       [ 9, 11]])

In [94]:
# slice 4 , 7
a2[1, 0::3]

array([4, 7])

In [95]:
# slice 1  , 2 , 3  , 5 , 6 , 7
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

#### 3-D Slicing 

In [96]:
a3 = np.arange(27).reshape(3 , 3 , 3)

In [97]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
# Take out the middle 2d array
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
# Take out alternate 2D arrays
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
# Print 2nd row of 1st 2D Array
a3[0 , 1]

array([3, 4, 5])

In [102]:
# 2nd row of every 2d Array

a3[0: , 1]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [103]:
# 4, 5 , 7 , 8 from 1st 2-D array and 22 , 23 , 25 , 26 from last 2-D array 

a3[0::2 , 1: , 1:]

array([[[ 4,  5],
        [ 7,  8]],

       [[22, 23],
        [25, 26]]])

In [104]:
# 0 , 2 , 18 , 20 
a3[0::2 , 0 , 0::2]

array([[ 0,  2],
       [18, 20]])

#### Iterating 

In [105]:
for i in a1 :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [106]:
for i in  a2 : 
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [107]:
for i in a3 : 
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


#### To go to each items of the 2-d/3-d array 

In [108]:
for i in np.nditer(a2): 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [109]:
for i in np.nditer(a3): 
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Transpose

In [110]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Ravel

In [113]:
a2.ravel() # => Used to convert any array into 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

#### Horizontal Stacking 

In [115]:
# Shapes should be same 

In [116]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12 , 24).reshape(3,4)

In [118]:
np.hstack((a4 , a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [119]:
np.hstack((a4 , a5 , a4 , a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

#### Vertical Stacking 

In [120]:
np.vstack((a4 , a5 ))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
np.vstack((a4 , a5 , a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Splitting

In [122]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
np.hsplit(a4 , 2) #np.hsplit(array, No. of equal parts we want to cut)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [125]:
np.hsplit(a4 , 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [126]:
np.vsplit(a4 , 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]